# https://taskfile.dev

version: '3'

tasks:
  release:
    vars:
      TAG:
        sh: 'date +%Y.%m.%d'
    cmds:
      - 'git tag -m {{.TAG}} {{.TAG}}'
      - 'git push --tags'
      - 'goreleaser release --clean'
  apply:
    vars:
      HOSTNAME:
        sh: hostname
    cmds:
      - home-manager switch --flake '.#carlos@{{.HOSTNAME}}'
