# https://taskfile.dev

version: '3'

vars:
  HOSTNAME:
    sh: "hostname | sed 's/\\.local//'"

tasks:
  release:
    vars:
      TAG:
        sh: 'date +%Y.%m.%d'
    cmds:
      - 'git tag -m {{.TAG}} {{.TAG}}'
      - 'git push --tags'
      - 'goreleaser release --clean'
  apply:
    cmds:
      - home-manager switch --flake '.#carlos@{{.HOSTNAME}}'
      - task: apply_darwin
  apply_darwin:
    internal: true
    status:
      - "test $(uname -s) -ne Darwin"
    cmds:
      - nix build ./\#darwinConfigurations.{{ .HOSTNAME }}.system
      - ./result/sw/bin/darwin-rebuild switch --flake .
