confirm-before-quit = false

# from https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/refs/heads/master/rio/GruvboxDarkHard.toml
[colors]
background = '#1b1b1b'
foreground = '#ebdbb2'
selection-background = '#665c54'
selection-foreground = '#ebdbb2'
cursor = '#ebdbb2'
black = '#1b1b1b'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'
light_black = '#928374'
light_red = '#fb4934'
light_green = '#b8bb26'
light_yellow = '#fabd2f'
light_blue = '#83a598'
light_magenta = '#d3869b'
light_cyan = '#8ec07c'
light_white = '#ebdbb2'

[cursor]
shape = 'block'
blinking = false
blinking-interval = 800

[editor]
program = "nvim"
args = []

[window]
mode = "maximized"

[renderer]
performance = "high"
backend = "Metal"

[keyboard]
use-kitty-keyboard-protocol = true

[fonts]
family = "TX-02"
size = 13
extras = [{ family = "JetBrainsMono Nerd Font Mono" }]
features = ["zero", "calt", "liga"]

fonts.symbol-map = [
  # powerline
  { start = "e0b0", end = "e0b3", font-family = "JetBrainsMono Nerd Font Mono" },
  { start = "e0b4", end = "e0c8", font-family = "JetBrainsMono Nerd Font Mono" },
  { start = "e0cc", end = "e0d4", font-family = "JetBrainsMono Nerd Font Mono" },
  { start = "e0ca", end = "e0ca", font-family = "JetBrainsMono Nerd Font Mono" },

  # font-awesome
  { start = "f000", end = "f2e0", font-family = "JetBrainsMono Nerd Font Mono" },
  { start = "e200", end = "e2a9", font-family = "JetBrainsMono Nerd Font Mono" },

  # seti-ui
  { start = "e5fa", end = "e6b1", font-family = "JetBrainsMono Nerd Font Mono" },

  # codicons
  { start = "ea60", end = "ebeb", font-family = "JetBrainsMono Nerd Font Mono" },
]
